[phases.preInstall]
cmds = ["git config --global url.\"https://${GITHUB_TOKEN}:x-oauth-basic@github.com/\".insteadOf \"https://github.com/\""]
dependsOn = ["setup"]

[phases.install]
dependsOn = ["preInstall"]
