[build]
builder = "RAILPACK"

[build.env]
NIXPACKS_INSTALL_CMD = "git config --global url.\"https://${GITHUB_TOKEN}:x-oauth-basic@github.com/\".insteadOf \"https://github.com/\" && poetry install --no-interaction --no-ansi --only main --no-root"

[deploy]
startCommand = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
